{"name": "test_login_2_exception[item1]", "status": "passed", "parameters": [{"name": "item", "value": "{'user': '', 'pwd': 'python', 'Expected': '请输入手机号'}"}], "start": 1605260772998, "stop": 1605260773348, "uuid": "6f3ba202-9a44-4ddf-9960-b5a7f0b63219", "historyId": "ccb86fe63c5fff69cbede6bf1158464d", "fullName": "Case.test_login_pytest.TestLogin#test_login_2_exception[item1]", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-CP63FEL"}, {"name": "thread", "value": "10712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_login_pytest"}]}