{"name": "test_login_2_exception[item0]", "status": "passed", "parameters": [{"name": "item", "value": "{'user': '18684720333', 'pwd': '', 'Expected': '请输入密码'}"}], "start": 1605260771694, "stop": 1605260772134, "uuid": "b45939c8-5b0c-4259-8239-50ec06a9b87c", "historyId": "ff06359a70cc528f731d37f0972956a1", "fullName": "Case.test_login_pytest.TestLogin#test_login_2_exception[item0]", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-CP63FEL"}, {"name": "thread", "value": "10712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_login_pytest"}]}